config/routes.rb
Cibbanktask::Application.routes.draw do

  get "users/edit"

  put "users/update"

  resources :payroll_employees
  resources :payrolls
  resources :employees
  resources :companies
   devise_for :users

   get "users/requestpassword"
   get "users/signoutpath"
   post "users/sendrequestpassword" #=> "users#sendrequestpassword"

   post "payrolls/create"
   post "payrolls/confirm"

root to: 'static_pages#home'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  password_changed_at    :datetime
#  user_name              :string(255)
#  company_id             :integer          default(0)
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :password_expirable ,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,:company_id,:user_name
 validates_uniqueness_of :email
  # attr_accessible :title, :body
   belongs_to :company



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  respond_to :html
before_filter :authenticate_user! , only: [:edit, :update ] 
  
 def edit
  @user = current_user
    respond_with(@user)
  
  end

  def update

    @user = User.find_by_email(params[:user][:email])
    if @user.update_attributes(params[:user])
    flash[:success] = "Profile updated"
    redirect_to root_path
  else
    render 'edit'
  end
  end

  def requestpassword
    
  end

  def sendrequestpassword

      @user = User.find_by_email(params[:email])

      if @user 
        UserRequestPassword.send_request_password(@user).deliver
        flash[:success] = "Email Send!"
           redirect_to root_path , :notice => "Email Send" 
      else
        flash[:notice] = "Email not found"
        render :requestpassword
      end 
  end

  def signoutpath
#      flash[:error] = "Your account is expired. Please contact Navanti for renewal."
        @user = current_user
        @passwordgenerate =  (0...8).map { (65 + rand(26)).chr }.join 
        @user.update_attributes(password: @passwordgenerate , password_confirmation: @passwordgenerate) 
        sign_out :user if user_signed_in?
        redirect_to root_path, notice: "Signed out successfully."  
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user_info.html.erb
<% @ary = Payroll.find_all_by_company_id(current_user.company_id).map{ |d| d.payrolls_creation_date.strftime('%m %y') }.uniq %>
     
<div class="btn-group"> 
<% if current_user.company_id == 0 %>

  <%= link_to "Create company", new_company_path ,  :class => "btn btn-default"  %>

<% else %>


<%= link_to "Add new employees", new_employee_path ,  :class => "btn btn-default"%>
<%= link_to "List of employees", employees_path ,  :class => "btn btn-default"%>
<% if !@ary.include?(DateTime.now.to_date.strftime('%m %y')) %>
<%= link_to "Create payroll", new_payroll_path ,  :class => "btn btn-default" %>

<% end %>


</div>
<br>
<br>

<p>Welcome  <%= current_user.email %></p>
<% @companyob =Company.find_by_id(current_user.company_id) %>
<% @payrolls = Payroll.find_all_by_company_id(current_user.company_id,  order: "id") %>
<p><b>Company Name :</b><%= @companyob.company_name %>  </p>
<p> <b>Total Payrolls :</b><%= @payrolls.count %></p>

<br>
<br>
<ul class="nav nav-tabs nav-justified">
  <li class="active"><a href="#">Payroll info</a></li> </ul>  

<br>

<% @payrolls.each do |payrollob| %>
<div class="jumbotron payroll" >

<table border="0" style="width:100%">
  <tr>
    <td><b>Payroll For <%= payrollob.payrolls_creation_date.strftime('%B-%y')%></b></td>

    <td>
    	<table border="0" style="width:100%">
			<tr>
				<td><p> <b>Creation date:  </b> <%= payrollob.payrolls_creation_date.strftime('%d-%m-%y') %> </p></td>
				<td><p> <b>Value date:  </b><%= payrollob.payrolls_value_day.strftime('%d-%m-%y') %></p></td>
			</tr>
			<tr>
				<td><p> <b>Total employees:  </b><%= payrollob.payrolls_no_employees %></p></td>
				<td><p> <b>Total amount EGP: </b><%= payrollob.payroll_amount %></p></td>
			</tr>
			<tr>
				<td><p> <b>Total amount USD: </b><%= payrollob.payroll_amount_usd %></p></td>
			</tr>
		</table>
	</td>
    <td>
    	<table border="0" style="width:100%">
			<tr>
				<td>
					<%= link_to "Info", payrollob, :class => "btn btn-default", :style=> "padding:10px 20px"  %>
				</td>
				<td>
				    <% if !@ary.include?(DateTime.now.to_date.strftime('%m %y')) %>
					<%= link_to "Create payroll", new_payroll_path ,  :class => "btn btn-default" %>
					<% end %>
				</td>
			</tr>
		</table>
	</td>
  </tr>
</table>  
</div>
<br >
<br >
 <% end %>




 <% end %>

app/views/users/edit.html.erb
<%= form_for(@user , url:{action: "update",:controller => "users" } ,html: {method: :put}) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  <%= f.label :user_name %>  
<%= f.text_field :user_name %>
</div>
<div class="field">
<%= f.label :email %>
<%= f.text_field :email %>
</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/requestpassword.html.erb
<h2>CIB Bank | Log in</h2>



<%= form_tag users_sendrequestpassword_path do  %>

  <div class="field">
    <%= label_tag :email %><br />
    <%= email_field_tag :email %>
  </div>

  <div class="actions">
    <%= submit_tag "Send Password" %>
  </div>


<% end %>