config/routes.rb
Cibbanktask::Application.routes.draw do

  get "users/edit"

  put "users/update"

  resources :payroll_employees
  resources :payrolls
  resources :employees
  resources :companies
   devise_for :users

   get "users/requestpassword"
   get "users/signoutpath"
   post "users/sendrequestpassword" #=> "users#sendrequestpassword"

   post "payrolls/create"
   post "payrolls/confirm"

root to: 'static_pages#home'

end

app/models/payroll_employee.rb
# == Schema Information
#
# Table name: payroll_employees
#
#  id          :integer          not null, primary key
#  amount      :float            default(0.0)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  employee_id :integer
#  payroll_id  :integer
#

class PayrollEmployee < ActiveRecord::Base
 
  attr_accessible :amount ,:payroll_id,:employee_id
    belongs_to :payroll
    belongs_to :employee

  validates :employee_id, presence: true
  validates :payroll_id, presence: true
  validates_uniqueness_of :payroll_id, :scope => :employee_id

  validates :amount, presence: true ,:format => { :with => /^\d+??(?:\.\d{0,2})?$/  }


end

app/controllers/payroll_employees_controller.rb
class PayrollEmployeesController < ApplicationController
  before_filter :set_payroll_employee, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user! 
  
  respond_to :html

  def index
    @payroll_employees = PayrollEmployee.all
    respond_with(@payroll_employees)
  end

  def show
    respond_with(@payroll_employee)
  end

  def new
    @payroll_employee = PayrollEmployee.new
    respond_with(@payroll_employee)
  end

  def edit
  end

  def create
    @payroll_employee = PayrollEmployee.new(params[:payroll_employee])
    @payroll_employee.save
    respond_with(@payroll_employee)
  end

  def update
    @payroll_employee.update_attributes(params[:payroll_employee])
    respond_with(@payroll_employee)
  end

  def destroy
    @payroll_employee.destroy
    respond_with(@payroll_employee)
  end

  private
    def set_payroll_employee
      @payroll_employee = PayrollEmployee.find(params[:id])
    end
end

app/helpers/payroll_employees_helper.rb
module PayrollEmployeesHelper
end

app/views/payroll_employees/_form.html.erb
<%= form_for(@payroll_employee) do |f| %>
  <% if @payroll_employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@payroll_employee.errors.count, "error") %> prohibited this payroll_employee from being saved:</h2>

      <ul>
      <% @payroll_employee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :amount %><br />
 <%= f.number_field :amount ,:class => 'text_field', :step => 0.01 %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/payroll_employees/edit.html.erb
<h1>Editing payroll_employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @payroll_employee %> |
<%= link_to 'Back', payroll_employees_path %>

app/views/payroll_employees/index.html.erb
<h1>Listing payroll_employees</h1>

<table>
  <tr>
    <th>Amount</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @payroll_employees.each do |payroll_employee| %>
  <tr>
    <td><%= payroll_employee.amount %></td>
    <td><%= link_to 'Show', payroll_employee %></td>
    <td><%= link_to 'Edit', edit_payroll_employee_path(payroll_employee) %></td>
    <td><%= link_to 'Destroy', payroll_employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Payroll employee', new_payroll_employee_path %>

app/views/payroll_employees/new.html.erb
<h1>New payroll_employee</h1>

<%= render 'form' %>

<%= link_to 'Back', payroll_employees_path %>

app/views/payroll_employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Amount:</b>
  <%= @payroll_employee.amount %>
</p>


<%= link_to 'Edit', edit_payroll_employee_path(@payroll_employee) %> |
<%= link_to 'Back', payroll_employees_path %>